### ISSUE TITLE
關於 curl 那邊 json 語法錯誤

### ISSUE THREAD

**Issue by wolke1007** [twtrubiks/docker-elk-tutorial#1]
curl 那邊之所以錯誤是因為 json 要用雙引號，我跳脫後可以使用希望有幫上忙
`
curl -XPOST -D- "http://localhost:5601/api/saved_objects/index-pattern" \
    -H "Content-Type: application/json" \
    -H "kbn-version: 6.1.0" \
    -d "{\"attributes\":{\"title\":\"logstash-*\",\"timeFieldName\":\"@timestamp\"}}"
`

**Comment by twtrubiks** [comment]
@wolke1007 謝謝回復, 我已經太久沒用 windows 了XD

**Comment by wolke1007** [comment]
噢 不是，與 windows 無關用 Mac 也會報錯，是 json 格式錯誤才會造成這個問題
X  {'key': 'value'}
O  {"key": "value"}

另外，感謝這篇教學讓沒ELK基礎的人也能上手這樣 :)
cheers
